name: frontend-starter

services:
  frontend:
    container_name: frontend
    image: frontend-starter/frontend:${APP_VERSION:-0.0.0}
    build:
      context: ../../
      dockerfile: ./docker/Frontend.Dockerfile
      args:
        DOCKER_REGISTRY: $DOCKER_REGISTRY
        NODEJS_BASE_IMAGE: $NODEJS_BASE_IMAGE
        NGINX_BASE_IMAGE: $NGINX_BASE_IMAGE
        FRONTEND_REGISTRY: $FRONTEND_REGISTRY
      target: final
    restart: unless-stopped
    environment:
      - APP_VERSION=$APP_VERSION
      - API_HOST=$API_HOST
      - HOST_PROTOCOL=$HOST_PROTOCOL
      - KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID
      - KEYCLOAK_CODE=$KEYCLOAK_CODE
      - KEYCLOAK_REALM=$KEYCLOAK_REALM
      - KEYCLOAK_URL=$KEYCLOAK_URL
    ports:
      - '3000:8080'
    extra_hosts:
      - 'host.docker.internal:host-gateway'


volumes:
  minio_data:
  pg_data:
  kpg_data:
